config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: ''

  # SubDomain - Admin
  constraints subdomain: 'admin' do
    get '/' => 'admin/home#index'
    
    namespace :admin, path: '/' do
      resources :products, :path => "promotions", as: "promotions"
      resources :applicants
    end

    # get '/users' => 'admin/admin#users'
    # patch 'users/:id' => 'admin/users_admin#update', as: :user
  end
  
  # V1 Default Website
  # namespace :v1, path: '' do
  #   resources :products, only: [:index, :show], :path => "promotion", as: "promotion" do 
  #     post "applicant_apply" => 'products#applicant_apply', as: :applicants
  #   end
  #   get '/menu-v1' => "home#menu"
  # end 

  # V2 New Design Responsive
  namespace :v2, path: '' do
    get '/menu'     => "home#menu"
    get '/specials' => "home#specials"
    get '/about'    => "home#about_us"
    get '/contact'  => "home#contact"
    get '/order'    => "home#order"
    resources :contacts, only: [:create]
  end

  resources :promotions, only: [:index, :show], :path => "promotion", as: "promotion" do 
    post "applicant_apply" => 'promotions#applicant_apply', as: :applicants
  end

  # root 'products#index'
  root 'v2/home#index'
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/controllers/v2/contacts_controller.rb
class V2::ContactsController < V2::V2Controller
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # def index
  #   @contacts = Contact.all
  # end

  # def show
  # end

  # def new
  #   @contact = Contact.new
  # end

  # def edit
  # end

  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        
        name = params[:contact][:name]
        email = params[:contact][:email]
        message = params[:contact][:message]
        ContactMailer.contact_email(name, email, message).deliver


        format.html { redirect_to :back, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
        format.js   {}
      else
        format.html { render :back }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
        format.js   {}
      end
    end
  end

  # def update
  #   respond_to do |format|
  #     if @contact.update(contact_params)
  #       format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @contact }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @contact.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # def destroy
  #   @contact.destroy
  #   respond_to do |format|
  #     format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_contact
    #   @contact = Contact.find(params[:id])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :message)
    end
end

app/controllers/v2/home_controller.rb
class V2::HomeController < V2::V2Controller
	
  def index
  end

  def menu
  end

  def specials
  end

  def about_us
  end

  def contact
  end
  
  def order
  end
end

app/controllers/v2/order_controller.rb
class V2::OrderController < V2::V2Controller

    def index
    end
    
end

app/controllers/v2/v2_controller.rb
class V2::V2Controller < ApplicationController
	layout "v2"
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/v2/contacts/_form.html.erb
<%= form_for(contact) do |f| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :message %>
    <%= f.text_area :message %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/v2/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/v2/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.message %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/v2/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/v2/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Message:</strong>
  <%= @contact.message %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>