config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: ''

  # SubDomain - Admin
  constraints subdomain: 'admin' do
    get '/' => 'admin/home#index'
    
    namespace :admin, path: '/' do
      resources :products, :path => "promotions", as: "promotions"
      resources :applicants
    end

    # get '/users' => 'admin/admin#users'
    # patch 'users/:id' => 'admin/users_admin#update', as: :user
  end
  
  # V1 Default Website
  # namespace :v1, path: '' do
  #   resources :products, only: [:index, :show], :path => "promotion", as: "promotion" do 
  #     post "applicant_apply" => 'products#applicant_apply', as: :applicants
  #   end
  #   get '/menu-v1' => "home#menu"
  # end 

  # V2 New Design Responsive
  namespace :v2, path: '' do
    get '/menu'     => "home#menu"
    get '/specials' => "home#specials"
    get '/about'    => "home#about_us"
    get '/contact'  => "home#contact"
    get '/order'    => "home#order"
    resources :contacts, only: [:create]
  end

  resources :promotions, only: [:index, :show], :path => "promotion", as: "promotion" do 
    post "applicant_apply" => 'promotions#applicant_apply', as: :applicants
  end

  # root 'products#index'
  root 'v2/home#index'
end

app/controllers/v2/contacts_controller.rb
class V2::ContactsController < V2::V2Controller
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # def index
  #   @contacts = Contact.all
  # end

  # def show
  # end

  # def new
  #   @contact = Contact.new
  # end

  # def edit
  # end

  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        
        name = params[:contact][:name]
        email = params[:contact][:email]
        message = params[:contact][:message]
        ContactMailer.contact_email(name, email, message).deliver


        format.html { redirect_to :back, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
        format.js   {}
      else
        format.html { render :back }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
        format.js   {}
      end
    end
  end

  # def update
  #   respond_to do |format|
  #     if @contact.update(contact_params)
  #       format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @contact }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @contact.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # def destroy
  #   @contact.destroy
  #   respond_to do |format|
  #     format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_contact
    #   @contact = Contact.find(params[:id])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :message)
    end
end

app/controllers/v2/home_controller.rb
class V2::HomeController < V2::V2Controller
	
  def index
  end

  def menu
  end

  def specials
  end

  def about_us
  end

  def contact
  end
  
  def order
  end
end

app/controllers/v2/order_controller.rb
class V2::OrderController < V2::V2Controller

    def index
    end
    
end

app/controllers/v2/v2_controller.rb
class V2::V2Controller < ApplicationController
	layout "v2"
end

app/views/v2/shared/_footer_two.html.erb
<div class="footer2">
    <div class="footer-socials">
        <ul class="socials-sh">
            <li>
                <a class="fa sh-socials-url fa-twitter" href="https://twitter.com/rbspizza1" title="Twitter" target="_blank"></a>
            </li>
            <li>
                <a class="fa sh-socials-url fa-facebook" href="https://www.facebook.com/rbspizzabellevue/" title="Facebook" target="_blank"></a>
            </li>
        </ul>
    </div>

    <div class="footer-content">
         ------ @ <%= DateTime.now.year %> ------
    </div>
    
    <!-- <div class="footer-content">
        @2017 7urkm3n. Made by 
        <a href="" title="">Pego</a> 
        &amp; 
        <a href="" title="HTML Themes">HTML</a>. 
    </div> -->
</div>

app/views/v2/shared/_mobile_side_bar.html.erb
<div class="mobile-menu-wrapper">
    <div class="menu-main-nav-menu-container">
        <ul id="menu-main-nav-menu-1" class="mobile-menu">
            <%= content_tag(:li, class: "menu-item menu-item-home #{current_page_v2(v2_order_path)}") do %>
                <%= link_to "Order Online", v2_order_path %>
            <% end %>
            <%= content_tag(:li, class: "menu-item menu-item-home #{current_page_v2(root_path)}") do %>
                <%= link_to "Home", root_path %>
            <% end %>
            <%= content_tag(:li, class: "menu-item #{current_page_v2(v2_menu_path)}") do %>
                <%#= link_to "Menu", v2_menu_path %>
            <% end %>
            <%= content_tag(:li, class: "menu-item #{current_page_v2(v2_specials_path)}") do %>
                <%#= link_to "Specials", v2_specials_path %>
            <% end %>
            <%= content_tag(:li, class: "menu-item #{current_page_v2(v2_contact_path)}") do %>
                <%= link_to "Contact", v2_contact_path %>
            <% end %>
            <%= content_tag(:li, class: "menu-item") do %>
                <%#= link_to "PROMOTIONS", promotion_index_path %>
            <% end %>
        </ul>
    </div>
</div>

app/views/v2/shared/_side_bar.html.erb
<style type="text/css">
#order-online-sidebar{
    color: #fab940;
    text-decoration: underline;
    font-weight: bold;
    font-size: 25px;
}
</style>
<div id="header" class="header-wrapper">
    <div class="logo">
        <a href="/" title="RBs Pizza">

            <img class="logoImage" src="/assets/v2/images/logo.png" alt="RBs Pizza" /><img class="logoImageRetina" src="/assets/v2/images/logo-retina.png" alt="RBs Pizza" />

        </a>
        <h4 class='center' style='color: #fab940'>Welcome to our New Website</h4>
        <div class="clear"></div>
    </div>
    <div class="menu-wrapper">
        <div class="main-menu">
            <div class="menu-main-nav-menu-container">
            

                <ul id="menu-main-nav-menu" class="sf-menu">
                    <%= content_tag(:li, class: "menu-item menu-item-home #{current_page_v2(v2_order_path)}") do %>
                        <%= link_to "Order Online", v2_order_path %>
                    <% end %>

                    <%= content_tag(:li, class: "menu-item menu-item-home #{current_page_v2(root_path)}") do %>
                        <%= link_to "Home", root_path %>
                    <% end %>
                    <%= content_tag(:li, class: "menu-item #{current_page_v2(v2_menu_path)}") do %>
                        <%#= link_to "Menu", v2_menu_path %>
                    <% end %>
                    <%= content_tag(:li, class: "menu-item #{current_page_v2(v2_specials_path)}") do %>
                        <%#= link_to "Specials", v2_specials_path %>
                    <% end %>
                    <%= content_tag(:li, class: "menu-item #{current_page_v2(v2_contact_path)}") do %>
                        <%= link_to "Contact", v2_contact_path %>
                    <% end %>
                    <%= content_tag(:li, class: "menu-item") do %>
                        <%#= link_to "PROMOTIONS", promotion_index_path %>
                    <% end %>



                    <!-- <li class="menu-item"><a href="/specials">Specials</a></li> -->
                    <!-- <li class="menu-item"><a href="about.html">About us</a></li> -->
                    <!-- <li class="menu-item"><a href="contact.html">Contact</a></li> -->
                    <!-- <li class="menu-item"><a href="blog.html">Blog</a></li> -->
                </ul>
            </div>
        </div>
        <div class="menu-icons-inside">
            <div class="menu-icon menu-icon-mobile"><span class="menu-icon-create"></span></div>
        </div>
    </div>
    <div class="clear"></div>
    <div class="footer">
        <div class="footer-socials">
            <ul class="socials-sh">
                <li>
                    <a class="fa sh-socials-url fa-twitter" href="https://twitter.com/rbspizza1" title="Twitter" target="_blank"></a> 
                </li>
                <li>
                    <a class="fa sh-socials-url fa-facebook" href="https://www.facebook.com/rbspizzabellevue/" title="Facebook" target="_blank"></a>
                </li>
                <!-- <li><a class="fa sh-socials-url fa-linkedin" href="#" title="LinkedIn" target="_blank"></a></li> -->
                <!-- <li><a class="fa sh-socials-url fa-google-plus" href="#" title="Google Plus" target="_blank"></a></li> -->
            </ul>
        </div>
        <div class="footer-content">
             ------ @ <%= DateTime.now.year %> ------
        </div>
    </div>
</div>