config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: ''

  # SubDomain - Admin
  constraints subdomain: 'admin' do
    get '/' => 'admin/home#index'
    
    namespace :admin, path: '/' do
      resources :products, :path => "promotions", as: "promotions"
      resources :applicants
    end

    # get '/users' => 'admin/admin#users'
    # patch 'users/:id' => 'admin/users_admin#update', as: :user
  end
  
  # V1 Default Website
  # namespace :v1, path: '' do
  #   resources :products, only: [:index, :show], :path => "promotion", as: "promotion" do 
  #     post "applicant_apply" => 'products#applicant_apply', as: :applicants
  #   end
  #   get '/menu-v1' => "home#menu"
  # end 

  # V2 New Design Responsive
  namespace :v2, path: '' do
    get '/menu'     => "home#menu"
    get '/specials' => "home#specials"
    get '/about'    => "home#about_us"
    get '/contact'  => "home#contact"
    get '/order'    => "home#order"
    resources :contacts, only: [:create]
  end

  resources :promotions, only: [:index, :show], :path => "promotion", as: "promotion" do 
    post "applicant_apply" => 'promotions#applicant_apply', as: :applicants
  end

  # root 'products#index'
  root 'v2/home#index'
end

app/models/product.rb
class Product < ApplicationRecord
	mount_uploader :image, ProductUploader
	has_many :applicants
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::AdminController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    if params[:destroy]
        destroy
    end
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    # render plain: params.inspect

    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to admin_promotions_path, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to admin_promotions_path, notice: 'Promotion was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to admin_promotions_path, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :desc, :quantity, :image, :active)
    end
end

app/controllers/v1/products_controller.rb
class V1::ProductsController < V1::V1Controller
  layout "promotion"
  before_action :set_product, only: :show
  before_action :activated, only: :show

  def index
    products = Product.where(active: true)
    @first_4  = products.first(4)
    @last_all = products.offset(4)
  end

  def show
  end

  def applicant_apply
    applied_user = Applicant.where(email: params[:applicant][:email])

    @applicant = Applicant.new(applicant_params)
    @applicant.state = "PA"
    @applicant.product_id = params[:promotion_id].to_i

    respond_to do |format|
       # && applied_user.product_id != params[:promotion_id].to_i
      if (applied_user.length < 2) && @applicant.save
        full_name = "#{@applicant.first_name} #{@applicant.last_name}"
        email     = @applicant.email
        promotion = @applicant.product.title

        ApplicantMailer.no_reply_email(full_name, email, promotion).deliver
        # @data = {:status => 200, :message => "Successfully Payback Accepted !"}
        format.js {render 'applicant_apply', locals: {:status => 200, :message => "Successfully Payback Accepted !"}}
      else
        format.js {render 'applicant_apply', locals: {:status => 401, :message => "Unfortunately, Only two Promotions available for each applicant!"}}
      end
    end
  end


private
  def set_product
    @product = Product.find(params[:id])
  end

  def applicant_params
    params.require(:applicant).permit(:first_name, :last_name, :email, :address_line, :address_line_two, :city, :state, :zip_code, :phone_number)
  end

  def activated
    unless @product.active
      redirect_to v1_promotion_index_path
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_for (product), url: url, html:{class: 'form-horizontal form-label-left'} do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="item form-group">
    <%= f.label :title, class: 'control-label col-md-3 col-sm-3 col-xs-12' do %>
      Title: <span class="required">*</span>
    <% end %>

    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= f.text_field :title, class: 'form-control col-md-7 col-xs-12', placeholder: "Title", required: "required"%>
    </div>
  </div>

  <div class="item form-group">
    <%= f.label :desc, class: 'control-label col-md-3 col-sm-3 col-xs-12' do %>
      Description: <span class="required">*</span>
    <% end %>

    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= f.text_area :desc, class: 'form-control col-md-7 col-xs-12', placeholder: "Description of Promotion", required: "required"%>
    </div>
  </div>

  <div class="item form-group">
    <%= f.label :quantity, class: 'control-label col-md-3 col-sm-3 col-xs-12' do %>
      Quantity: <span class="required">*</span>
    <% end %>

    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= f.number_field :quantity, class: 'form-control col-md-7 col-xs-12', placeholder: "Quantity", required: "required"%>
    </div>
  </div>

  <div class="item form-group">
    <%= f.label :image, class: 'control-label col-md-3 col-sm-3 col-xs-12' do %>
      Image: <span class="required"><%= !@product.image? ? "*" : '' %></span>
    <% end %>

    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= f.file_field :image, class: 'form-control col-md-7 col-xs-12' %>
        <%= image_tag(product.image_url, size: "275") if @product.image? %>
        <%= f.hidden_field :image_cache %>
    </div>
  </div>

  <div class="item form-group">
    <%= f.label :active, class: 'control-label col-md-3 col-sm-3 col-xs-12' do %>
      Activate: <span class="required"></span>
    <% end %>

    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= f.check_box :active, class: 'form-control col-md-7 col-xs-12'%>
    </div>
  </div>


  <div class="ln_solid"></div>
  <div class="form-group">
    <div class="col-md-6 col-md-offset-3">
      <%= link_to "Cancel", admin_promotions_path, class: 'btn btn-primary' %>
      <%= f.submit 'Submit', class: 'btn btn-success' %>
    </div>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<div class="clearfix"></div>
<div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h1>Edit Promotion <small></small></h2>
        <ul class="nav navbar-left panel_toolbox">
          <li> <%= link_to 'Back', admin_promotions_path, class: 'btn btn-default btn-lg' %> </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
		<%= render partial: 'form', locals: {product: @product, url: admin_promotion_path} %>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/index.html.erb
<div class="page-title">
  <div class="title_left">
    <h2 id="notice"><%= notice %></h2>
    <h3>
        Promotions Total: <%= @products.length %>
        <br>
        <small> Activated Promotions will be checked </small>
      </h3>
  </div>
  <div class="title_right">
    <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
        <%= link_to "Add new a Promotion", new_admin_promotion_path, class: 'btn btn-primary pull-right' %>
    </div>
  </div>
</div>
<div class="clearfix"></div>

<div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h2>Responsive example <small>Users</small></h2>
        <ul class="nav navbar-right panel_toolbox">
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">Settings 1</a>
              </li>
              <li><a href="#">Settings 2</a>
              </li>
            </ul>
          </li>
          <!-- <li><a class="close-link"><i class="fa fa-close"></i></a></li> -->
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <p class="text-muted font-13 m-b-30">
          Responsive is an extension for DataTables that resolves that problem by optimising the table's layout for different screen sizes through the dynamic insertion and removal of columns from the table.
        </p>
        <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
          <thead>
            <tr>
              <th>Image</th>
              <th>Title</th>
              <th>Description</th>
              <th>Quantity</th>
              <th>Active</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
          <% @products.each do |product| %>
            <tr>
              <td><%= image_tag(product.image, size: "75") %></td>
              <td><%= product.title %></td>
              <td><%= product.desc %></td>
              <td><%= product.quantity %></td>
              <td><%= check_box_tag("active", "accepted", product.active, disabled: true) %></td>
              <td>
                <%= link_to 'Edit', edit_admin_promotion_path(product), class: 'btn btn-default '%>
                <%= link_to 'Destroy', admin_promotion_path(product, destroy: true), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'%>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>

      </div>
    </div>
  </div>
</div>

app/views/admin/products/new.html.erb
<div class="clearfix"></div>
<div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h1>New Promotion <small></small></h2>
        <ul class="nav navbar-left panel_toolbox">
          <li> <%= link_to 'Back', admin_promotions_path, class: 'btn btn-default btn-lg' %> </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
		<%= render partial: 'form', locals: {product: @product, url: admin_promotions_path} %>
      </div>
    </div>
  </div>
</div>