config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: ''

  # SubDomain - Admin
  constraints subdomain: 'admin' do
    get '/' => 'admin/home#index'
    
    namespace :admin, path: '/' do
      resources :products, :path => "promotions", as: "promotions"
      resources :applicants
    end

    # get '/users' => 'admin/admin#users'
    # patch 'users/:id' => 'admin/users_admin#update', as: :user
  end
  
  # V1 Default Website
  # namespace :v1, path: '' do
  #   resources :products, only: [:index, :show], :path => "promotion", as: "promotion" do 
  #     post "applicant_apply" => 'products#applicant_apply', as: :applicants
  #   end
  #   get '/menu-v1' => "home#menu"
  # end 

  # V2 New Design Responsive
  namespace :v2, path: '' do
    get '/menu'     => "home#menu"
    get '/specials' => "home#specials"
    get '/about'    => "home#about_us"
    get '/contact'  => "home#contact"
    get '/order'    => "home#order"
    resources :contacts, only: [:create]
  end

  resources :promotions, only: [:index, :show], :path => "promotion", as: "promotion" do 
    post "applicant_apply" => 'promotions#applicant_apply', as: :applicants
  end

  # root 'products#index'
  root 'v2/home#index'
end

app/models/applicant.rb
class Applicant < ApplicationRecord
	belongs_to :product

	def  full_name
	   "#{first_name} #{last_name}"
	end

	def  full_address
		address = "#{address_line}, #{city}, #{state}. #{zip_code}"
   		address = "#{address_line}, #{address_line_two}, #{city}, #{state}. #{zip_code}" if address_line_two.length >= 1
	   	return address
	end
end

app/controllers/admin/applicants_controller.rb
class Admin::ApplicantsController < Admin::AdminController
  before_action :set_applicant, only: [:show, :edit, :update, :destroy]

  def index
    @applicants = Applicant.all
  end

  def show
      if params[:destroy]
        destroy
      end
  end

  def new
    @applicant = Applicant.new
  end

  def edit
  end

  def create
    @applicant = Applicant.new(applicant_params)
    @applicant.state = "PA"
    @applicant.product_id = params[:product_id].to_i if params[:product_id]

    respond_to do |format|
      if @applicant.save
        format.html { redirect_to admin_applicants_path, notice: 'Applicant was successfully updated.' }
        format.json { render :show, status: :ok, location: @applicant }
        # format.json { render json: @applicant, status: 200}
      else
        format.html { render :new }
        format.json { render json: @applicant.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @applicant.update(applicant_params)
        format.html { redirect_to admin_applicants_path, notice: 'Applicant was successfully updated.' }
        format.json { render :show, status: :ok, location: @applicant }
      else
        format.html { render :edit }
        format.json { render json: @applicant.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @applicant.destroy
    respond_to do |format|
      format.html { redirect_to admin_applicants_path, notice: 'Applicant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_applicant
      @applicant = Applicant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def applicant_params
      params.require(:applicant).permit(:first_name, :last_name, :email, :address_line, :address_line_two, :city, :state, :zip_code, :phone_number)
    end
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/views/admin/applicants/_form.html.erb
<%= form_for (applicant), url: url, html:{class: 'form-horizontal form-label-left'} do |f| %>
  <% if applicant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(applicant.errors.count, "error") %> prohibited this applicant from being saved:</h2>

      <ul>
      <% applicant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="item form-group">
    <%= f.label :first_name, class: 'control-label col-md-3 col-sm-3 col-xs-12' do %>
      First Name: <span class="required">*</span>
    <% end %>

    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= f.text_field :first_name, class: 'form-control col-md-7 col-xs-12', placeholder: "First Name", required: "required"%>
    </div>
  </div>

  <div class="ln_solid"></div>
  <div class="form-group">
    <div class="col-md-6 col-md-offset-3">
      <%= link_to "Cancel", admin_applicants_path, class: 'btn btn-primary' %>
      <%= f.submit 'Submit', class: 'btn btn-success' %>
    </div>
  </div>
<% end %>

app/views/admin/applicants/edit.html.erb
<div class="clearfix"></div>
<div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h1>Edit Applicant Info <small></small></h2>
        <ul class="nav navbar-left panel_toolbox">
          <li> <%= link_to 'Back', admin_applicants_path, class: 'btn btn-default btn-lg' %> </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
		<%= render partial: 'form', locals: {applicant: @applicant, url: admin_applicant_path} %>
      </div>
    </div>
  </div>
</div>

app/views/admin/applicants/index.html.erb
<div class="page-title">
  <div class="title_left">
  <h2 id="notice"><%= notice %></h2>
    <h3>
        Applicants Total: <%= @applicants.length %>
<!--         <small> Active Promotions will be checked </small> -->
      </h3>
  </div>

  <div class="title_right">
    <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
        <%= link_to "Add new a Applicant", new_admin_applicant_path, class: 'btn btn-primary pull-right' %>
    </div>
  </div>
</div>
<div class="clearfix"></div>

<div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <ul class="nav navbar-right panel_toolbox">
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">Settings 1</a>
              </li>
              <li><a href="#">Settings 2</a>
              </li>
            </ul>
          </li>
          <!-- <li><a class="close-link"><i class="fa fa-close"></i></a></li> -->
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <p class="text-muted font-13 m-b-30">
          Responsive is an extension for DataTables that resolves that problem by optimising the table's layout for different screen sizes through the dynamic insertion and removal of columns from the table.
        </p>
        <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
          <thead>
            <tr>
              <th>Full Name</th>
              <th>Email</th>
              <th>Address</th>
              <th>Phone</th>
              <th>Promotion</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
          <% @applicants.each do |applicant| %>
            <tr>
              <td><%= applicant.full_name %></td>
              <td><%= applicant.email %></td>
              <td><%= applicant.full_address %></td>
              <td><%= applicant.phone_number %></td>
              <td><%= "ID: #{applicant.product.id} - #{applicant.product.title}"%></td>
              <td>
                <%= link_to 'Edit', edit_admin_applicant_path(applicant), class: 'btn btn-default '%>
                <%= link_to 'Destroy', admin_applicant_path(applicant, destroy: true), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'%>
              </td>
                


              </td></td>
            </tr>
          <% end %>
          </tbody>
        </table>

      </div>
    </div>
  </div>
</div>





<% block do %>
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= link_to 'Show', admin_blog_path(blog) %></td>
        <td><%= link_to 'Edit', edit_admin_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', admin_blog_path(blog), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_admin_blog_path %>
<% end %>

app/views/admin/applicants/new.html.erb
<div class="clearfix"></div>
<div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h1>New Applicant <small></small></h2>
        <ul class="nav navbar-left panel_toolbox">
          <li> <%= link_to 'Back', admin_applicants_path, class: 'btn btn-default btn-lg' %> </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
		<%= render partial: 'form', locals: {applicant: @applicant, url: new_admin_applicant_path} %>
      </div>
    </div>
  </div>
</div>